package main.java.Model.Entity;

import java.time.LocalTime;

public class Branch {
    private int branch_ID;
    private String name;
    private String contact_number;
    private String email;
    private int max_slots;
    private String location;
    private LocalTime opening_time;
    private LocalTime closing_time;

    // === CONSTRUCTORS ===

    /**
     * Default Constructor
     */
    public Branch() {}

    /**
     * Full constructor for reading existing records from the database.
     */
    public Branch(int branch_ID, String name, String contact_number,
                  String email, int max_slots, String location,
                  LocalTime opening_time, LocalTime closing_time) {
        this.branch_ID = branch_ID;
        this.name = name;
        this.contact_number = contact_number;
        this.email = email;
        this.max_slots = max_slots;
        this.location = location;
        this.opening_time = opening_time;
        this.closing_time = closing_time;
    }

    /**
     * Constructor for creating a new branch before insertion (ID is generated by DB).
     */
    public Branch(String name, String contact_number, String email,
                  int max_slots, String location,
                  LocalTime opening_time, LocalTime closing_time) {
        this.name = name;
        this.contact_number = contact_number;
        this.email = email;
        this.max_slots = max_slots;
        this.location = location;
        this.opening_time = opening_time;
        this.closing_time = closing_time;
    }

    // === GETTERS and SETTERS

    public int getBranch_ID() {return branch_ID;}
    public String getName() {return name;}
    public String getContact_number() {return contact_number;}
    public String getEmail() {return email;}
    public int getMax_slots() {return max_slots;}
    public String getLocation() {return location;}
    public LocalTime getOpening_time() {return opening_time;}
    public LocalTime getClosing_time() {return closing_time;}

    public void setBranch_ID(int branch_ID) {this.branch_ID = branch_ID;}
    public void setName(String name) {this.name = name;}
    public void setContact_number(String contact_number) {this.contact_number = contact_number;}
    public void setEmail(String email) {this.email = email;}
    public void setMax_slots(int max_slots) {this.max_slots = max_slots;}
    public void setLocation(String location) {this.location = location;}
    public void setOpening_time(LocalTime opening_time) {this.opening_time = opening_time;}
    public void setClosing_time(LocalTime closing_time) {this.closing_time = closing_time;}

    // === UTILITY METHOD ===

    /**
     * Checks if the current time falls within the branch's operating hours.
     * @param currentTime The time to check against operating hours.
     * @return true if the branch is currently open, false otherwise.
     */
    public boolean isOpen(LocalTime currentTime) {
        if (opening_time != null && closing_time != null) {
            return !currentTime.isBefore(opening_time) && !currentTime.isAfter(closing_time);
        }
        return true;
    }

    @Override
    public String toString() {
        return "Branch{" +
                "Branch_ID: " + branch_ID +
                ", Name: " + name +
                ", Max Slots: " + max_slots +
                ", Location: " + location+ '\'' + '}';
    }
}
