package main.java.Model.Entity;

/**
 * Maps to the 'vehicles' table in the database.
 * Represents a car, motorcycle, or other vehicle registered by a User.
 */
public class Vehicle {
    private int vehicle_id;
    private int user_id;
    private String plate_number;
    private String vehicle_type;
    private String vehicle_brand;

    // === CONSTRUCTORS ===

    /**
     * Default Constructor
     */
    public Vehicle(){}

    /**
     * Full Constructor for reading existing records from the database.
     * @param vehicle_id
     * @param user_id
     * @param plate_number
     * @param vehicle_type
     * @param vehicle_brand
     */
    public Vehicle(int vehicle_id, int user_id, String plate_number, String vehicle_type, String vehicle_brand) {
        this.vehicle_id = vehicle_id;
        this.user_id = user_id;
        this.plate_number = plate_number;
        this.vehicle_type = vehicle_type;
        this.vehicle_brand = vehicle_brand;
    }

    /**
     * Constructor for creating a new vehicle before insertion (ID is generated by DB).
     * @param user_id
     * @param plate_number
     * @param vehicle_type
     * @param vehicle_brand
     */
    public Vehicle(int user_id, String plate_number, String vehicle_type, String vehicle_brand) {
        this.user_id = user_id;
        this.plate_number = plate_number;
        this.vehicle_type = vehicle_type;
        this.vehicle_brand = vehicle_brand;
    }

    // === GETTERS and SETTERS
    public int getVehicle_id() {return vehicle_id;}
    public int getUser_id() {return user_id;}
    public String getPlate_number() {return plate_number;}
    public String getVehicle_type() {return vehicle_type;}
    public String getVehicle_brand() {return vehicle_brand;}

    public void setVehicle_id(int vehicle_id) {this.vehicle_id = vehicle_id;}
    public void setUser_id(int user_id) {this.user_id = user_id;}
    public void setPlate_number(String plate_number) {this.plate_number = plate_number;}
    public void setVehicle_type(String vehicle_type) {this.vehicle_type = vehicle_type;}
    public void setVehicle_brand(String vehicle_brand) {this.vehicle_brand = vehicle_brand;}

    @Override
    public String toString() {
        return "Vehicle{" +
                "Vehicle ID: " + vehicle_id +
                ", User ID: " + user_id +
                ", Plate Number: " + plate_number +
                ", Vehicle Type: " + vehicle_type +
                ", Vehicle Brand: " + vehicle_brand + '}';
    }
}
