package Model.Entity;

import java.math.BigDecimal;

/**
 * Maps to the 'pricing' table in the database.
 * Represents the pricing of the branch for a slot_Type
 */
public class Pricing {
    private int pricing_ID;
    private int branch_ID;
    private SlotType slot_type;
    private BigDecimal hourly_rate;
    private BigDecimal overtime_rate;

    // === CONSTRUCTORS ===

    /**
     * Default Constructor
     */
    public Pricing() {}

    /**
     * Full Constructor for reading existing records from the database
     * @param pricing_ID The unique ID of the pricing (PK)
     * @param branch_ID The ID of the branch this rules applies to (FK)
     * @param slot_type The type of slot this price applies to
     * @param hourly_rate The base charge per hour
     * @param overtime_rate The increased rate charged for parking beyond the allowed time
     */
    public Pricing(int pricing_ID, int branch_ID, SlotType slot_type, BigDecimal hourly_rate, BigDecimal overtime_rate) {
        this.pricing_ID = pricing_ID;
        this.branch_ID = branch_ID;
        this.slot_type = slot_type;
        this.hourly_rate = hourly_rate;
        this.overtime_rate = overtime_rate;
    }

    /**
     *      * Constructor for creating a new pricing rule before insertion (ID is generated by DB).
     * @param branch_ID The ID of the branch this rules applies to (FK)
     * @param slot_type The type of slot this price applies to
     * @param hourly_rate The base charge per hour
     * @param overtime_rate The increased rate charged for parking beyond the allowed time
     */
    public Pricing(int branch_ID, SlotType slot_type, BigDecimal hourly_rate, BigDecimal overtime_rate) {
        this.branch_ID = branch_ID;
        this.slot_type = slot_type;
        this.hourly_rate = hourly_rate;
        this.overtime_rate = overtime_rate;
    }

    // === GETTERS and SETTERS ===
    public int getPricing_ID() {return pricing_ID;}
    public int getBranch_ID() {return branch_ID;}
    public SlotType getSlot_type() {return slot_type;}
    public BigDecimal getHourly_rate() {return hourly_rate;}
    public BigDecimal getOvertime_rate() {return overtime_rate;}

    public void setPricing_ID(int pricing_ID) {this.pricing_ID = pricing_ID;}
    public void setBranch_ID(int branch_ID) {this.branch_ID = branch_ID;}
    public void setSlot_type(SlotType slot_type) {this.slot_type = slot_type;}
    public void setHourly_rate(BigDecimal hourly_rate) {this.hourly_rate = hourly_rate;}
    public void setOvertime_rate(BigDecimal overtime_rate) {this.overtime_rate = overtime_rate;}

    @Override
    public String toString() {
        return "Pricing{" +
                "Pricing ID: " + pricing_ID +
                ", Branch ID: " + branch_ID +
                ", Slot Type: " + slot_type +
                ", Hourly Rate: " + hourly_rate + "}";
    }
}
